site_name: Projet Mauna

pages:
- ['index.md', 'Home']
- ['install-dev.md', 'Development']
- ['buildings/social.md', 'B창timents', 'Sociaux']
- ['buildings/environment.md', 'B창timents', 'Environnement']
- ['buildings/energy.md', 'B창timents', 'Energie']
- ['buildings/miscellaneous.md', 'B창timents', 'Divers']